### ISSUE TITLE
TimeSensorAsync breaks if target_time is timezone-aware

### ISSUE THREAD

**Issue by spatocode** [GitStartHQ/airflow-1#13]
### Description

```TimeSensorAsync``` fails with the following error ```if target_time``` is aware:

```[2022-06-29, 05:09:11 CDT] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/envs/production/lib/python3.9/site-packages/airflow/sensors/time_sensor.py", line 60, in execute
    trigger=DateTimeTrigger(moment=self.target_datetime),
  File "/opt/conda/envs/production/lib/python3.9/site-packages/airflow/triggers/temporal.py", line 42, in __init__
    raise ValueError(f"The passed datetime must be using Pendulum's UTC, not {moment.tzinfo!r}")
ValueError: The passed datetime must be using Pendulum's UTC, not Timezone('America/Chicago')
```

### Use case/motivation

Given the fact that ```TimeSensor``` correctly handles timezones (https://github.com/apache/airflow/pull/9882), this seems like a bug. ```TimeSensorAsync``` should be a drop-in replacement for ```TimeSensor```, and therefore should have the same timezone behavior.

### Related issues

```
#!/usr/bin/env python3
import datetime

from airflow.decorators import dag
from airflow.sensors.time_sensor import TimeSensor, TimeSensorAsync
import pendulum


@dag(
    start_date=datetime.datetime(2022, 6, 29),
    schedule_interval='@daily',
)
def time_sensor_dag():
    naive_time1 = datetime.time( 0,  1)
    aware_time1 = datetime.time( 0,  1).replace(tzinfo=pendulum.local_timezone())
    naive_time2 = pendulum.time(23, 59)
    aware_time2 = pendulum.time(23, 59).replace(tzinfo=pendulum.local_timezone())

    TimeSensor(task_id='naive_time1', target_time=naive_time1, mode='reschedule')
    TimeSensor(task_id='naive_time2', target_time=naive_time2, mode='reschedule')
    TimeSensor(task_id='aware_time1', target_time=aware_time1, mode='reschedule')
    TimeSensor(task_id='aware_time2', target_time=aware_time2, mode='reschedule')

    TimeSensorAsync(task_id='async_naive_time1', target_time=naive_time1)
    TimeSensorAsync(task_id='async_naive_time2', target_time=naive_time2)
    TimeSensorAsync(task_id='async_aware_time1', target_time=aware_time1)  # fails
    TimeSensorAsync(task_id='async_aware_time2', target_time=aware_time2)  # fails

dag = time_sensor_dag()
```
This can also happen if the ```target_time``` is naive and ```core.default_timezone = system```.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by spatocode** [comment]
Closed in #14
